app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField
from wtforms.validators import DataRequired


class PasswordPwnedForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Pwned?')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config

bootstrap = Bootstrap()


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)

    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.breaches import breaches_bp
    app.register_blueprint(breaches_bp)

    return app

app/breaches/__init__.py
from flask import Blueprint

breaches_bp = Blueprint("breaches_bp", __name__)

from . import routes

app/breaches/routes.py
from . import breaches_bp
from flask import render_template
from .services import breached_websites_service
import datetime


@breaches_bp.route("/breachedWebsites", methods=["GET"])
def breached_websites():
    json_response = breached_websites_service.breached_websites()
    return render_template("breached_websites.html", breached_websites=json_response)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from app.main import bp, forms
from flask import render_template, redirect, url_for, flash
from app.main.services import pwned_password_service


@bp.route("/", methods=["GET", "POST"])
def index():
    form = forms.PasswordPwnedForm()
    if form.validate_on_submit():
        pwned_service = pwned_password_service.PwnedPasswordService(form.password.data)
        pwned_count = pwned_service.pwned_count()
        pwned_count_str = "{:,}".format(pwned_count)

        if pwned_count > 0:
            flash(f"This password has appeared <strong>{pwned_count_str}</strong> times in compromised passwords dataset. "
                  f"If you are using this password anywhere, we strongly recommend you to change it immediately.", "pwned")
        elif pwned_count == 0:
            flash("This password was not found in any of the compromised passwords dataset available.", "not_pwned")
        else:
            flash("Pwned Password service is unavailable. Please try after some time. "
                  "We regret the inconvenience caused.", "service_unavailable")

        password_weaknesses = pwned_service.check_password_strength()
        for weakness in password_weaknesses:
            flash(f"{weakness} ", "password_weakness")

        return redirect(url_for("main.index"))

    return render_template("index.html", form=form)


@bp.route("/about")
def about():
    return render_template("about.html")

app/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-xs-12">
            <h2>About Pwned Credentials</h2>
            <p>
                This website has been built as an open source project aimed to provide users necessary information
                regarding data breaches. It utilizes the
                <a href="https://haveibeenpwned.com/API/v3" target="_blank" alt="API link">APIs</a> provided by
                <a href="https://haveibeenpwned.com/" target="_blank">haveibeenpwned.com</a>.
            </p>
            <p>
                Please refer <a href="https://haveibeenpwned.com/About" target="_blank">here</a> for
                further details. <br>
                
                    
                </a>
            </p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
{{super()}}
<link href="./static/images/favicon.ico" rel="icon">
{% endblock %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}
Pwned Credentials
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Pwned Credentials</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('breaches_bp.breached_websites')}}">Breached Websites</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.about')}}">About</a>
            </li>
        </ul>
    </div>
</nav>
{% endblock %}

app/templates/breached_websites.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2>Breached Websites</h2>
            <p>
                Details about the breached websites obtained from
                <a href="https://haveibeenpwned.com/" target="_blank">Have I Been Pwned</a>
            </p>
        </div>
    </div>
    {% for breach in breached_websites %}
    <div class="row justify-content-center" style="margin-top: 70px;">
        <div class="col-sm-2">
            <img class="img-fluid pwned-website-logo" src="{{breach.LogoPath}}" alt="{{breach.Name}} Logo">
        </div>
        <div class="col-sm-10">
            <h3>{{breach.Title}}</h3>
            <p>{{breach.Description | safe}}</p>
            <p>
                <strong>Breach date</strong>: {{breach.BreachDate | datetime("%Y-%m-%d", "%d %b, %Y")}}
                <br>
                <strong>Breached accounts</strong>: {{"{:,}".format(breach.PwnCount)}}
                <br>
                <strong>Breached data</strong>: {{breach.DataClasses | join(", ")}}
                <br>
                <a href="https://www.{{breach.Domain}}" alt="{{breach.Name}} link" target="_blank">
                    Click here to visit {{breach.Title}}
                </a>
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{%  endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container pwned-container">
    <div class="row h-100">
        <div class="col my-auto mx-auto">
            {% for error in form.password.errors %}
            <div class="alert alert-danger alert-dismissible fade show col-md-9 mx-auto" role="alert">
                {{ error }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}

            {% with messages = get_flashed_messages(category_filter=["pwned"]) %}
            {% if messages %}
            <div class="alert alert-danger alert-dismissible fade show col-md-9 mx-auto" role="alert">
                <h2 class="text_center">Pwned!</h2>
                {% for message in messages%}
                <p>
                    {{ message | safe }}
                </p>
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}

            {% with messages = get_flashed_messages(category_filter=["not_pwned"]) %}
            {% if messages %}
            <div class="alert alert-success alert-dismissible fade show col-md-9 mx-auto" role="alert">
                <h2 class="text_center">No pwnage found!</h2>
                {% for message in messages %}
                <p>
                    {{message | safe}}
                </p>
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}

            {% with messages = get_flashed_messages(category_filter=["service_unavailable"]) %}
            {% if messages %}
            <div class="alert alert-danger alert-dismissible fade show col-md-9 mx-auto" role="alert">
                <h2 class="text_center">Service unavailable!</h2>
                {% for message in messages %}
                <p>
                    {{message | safe}}
                </p>
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}

            {% with messages = get_flashed_messages(category_filter=["password_weakness"]) %}
            {% if messages %}
            <div class="alert alert-danger alert-dismissible fade show col-md-9 mx-auto" role="alert">
                <h2 class="text_center">Password Strength Weak!</h2>
                <ul>
                    {% for message in messages%}
                    <li>{{message | safe}}</li>
                    {% endfor %}
                    <li>
                        We strongly recommend you to read the
                        <a href="https://en.wikipedia.org/wiki/Password_strength#Guidelines_for_strong_passwords"
                           target="_blank"> guidelines for strong password here.</a>
                    </li>
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}

            <div class="col-md-9 px-0 mx-auto">
                <form action="/" method="post" novalidate>
                    {{ form.hidden_tag() }}
                    <div class="input-group mb-2">
                        {{ form.password(placeholder=form.password.label.text, class_="form-control form-control-lg") }}
                        <div class="input-group-append">
                            {{ form.submit(class_="btn btn-primary btn-lg") }}
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-9 px-0 mx-auto">
                <p>
                    Check here if your password has ever been compromised in a data breach. Breached passwords
                    are not suitable for usage. We also provide necessary information regarding your password
                    strength.
                </p>
            </div>
        </div>
    </div>

</div>

{% endblock %}